### ISSUE TITLE
Client-side?

### ISSUE THREAD

**Issue by alexiskattan** [nhunzaker/speakeasy#6]
Is there a way to make this client-side and run in the browser?

**Comment by nhunzaker** [comment]
Possibly! I do not currently test against the browser, but it's possible using a build tool such as [Browserify](https://github.com/substack/node-browserify) or [Webpack](webpack.github.io). 

The biggest challenge would be the over all file size. To calculate sentiment, [I'm using a rather large corpus of words](https://github.com/nhunzaker/speakeasy/blob/master/lib/sentiment/negative-words.js). This may be prohibitively large for your project.

Still, give it a shot!

**Comment by tarundhillon** [comment]
I did compile this using Browserify, was able to generate the QR Code but getting an "TypeError: item.copy is not a function" in the Buffer.concat function. Seems like a dependency is missing, any ideas how to fix ? Thanks
