### ISSUE TITLE
array.slice arguments error

### ISSUE THREAD

**Issue by joewashear007** [nhunzaker/speakeasy#8]
I have found a issues with your code that I am unsure how to fix. You are supplying too many argument to the slice function in `lib/classify/index.js` on line `203`. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice), the slice function should only have 2 arguments, not 3.

``` javascript
 owner = words.slice(prepIndex + 1, -1, detIndex).join(" ");
```

Thanks!

**Comment by nhunzaker** [comment]
Ack! The perils of viewing my own code from years ago. I'll dig into this.

**Comment by joewashear007** [comment]
Thanks. Also nice work by the way!

Joseph Livecchi
jjprograms.com

**Comment by soyjavi** [comment]
ey, still having the problem... any progress??

**Comment by nhunzaker** [comment]
Sorry... sent out a new release. Check out `speakeasy-nlp@0.2.12`
